export const NOTIFICATIONS_COUNT = 11;
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';
export const MARK_ALL_NOTIFICATIONS_AS_READ = 'MARK_ALL_NOTIFICATIONS_AS_READ';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_READ_STATUS_FILTER = 'SET_READ_STATUS_FILTER';
export const ReadStatusFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_READ: 'SHOW_READ',
  SHOW_UNREAD: 'SHOW_UNREAD',
};
export const CategoryFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_CRITICAL: 'SHOW_CRITICAL',
  SHOW_WARN: 'SHOW_WARN',
  SHOW_SUCCESS: 'SHOW_SUCCESS',
  SHOW_INFO: 'SHOW_INFO',
  SHOW_ERROR: 'SHOW_ERROR',
};
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SHOW_ANOTHER_PAGE = 'SHOW_ANOTHER_PAGE';
